### ISSUE TITLE
wrong `this` in lib

### ISSUE THREAD

**Issue by lewismoten** [lewismoten/riff-wave-reader#33]
Using v0.1.0 - calling `reader.readFromat()` throws an error. Looking at generated code, functional wrappers are redefining `this`

# Test
```js
const RiffReader = require("riff-wave-reader").Reader;

const file = path.join(__dirname, "hello.wav");
const reader = new RiffReader(file);
reader
  .readRiff()
  .then(reader.readFormat)
  .then(reader.readDataHeader)
  .then(() => {
    // readSample(channel, index) {
    console.log("GOT IT");
  })
  .catch(e => console.log("ERROR", e));
```
# Error
```bash
ERROR TypeError: Cannot read property 'format' of undefined
    at C:\dev\cute-piano-odyssey\node_modules\riff-wave-reader\lib\read-format-header.js:17:17
    at new Promise (<anonymous>)
    at readFormatHeader (C:\dev\cute-piano-odyssey\node_modules\riff-wave-reader\lib\read-format-header.js:16:10)
    at readFormat (C:\dev\cute-piano-odyssey\node_modules\riff-wave-reader\lib\index.js:35:53)
```

# v0.1.1 code source
```
_createClass(Reader, [{
    key: "readRiff",
    value: function readRiff() {
      return (0, _readRiffHeader.readRiffHeader)(this);
    }
  }, {
    key: "readFormat",
    value: function readFormat() {
      return (0, _readFormatHeader.readFormatHeader)(this);
    }
  }, {
```

**Comment by lewismoten** [comment]
This is a non-issue. Passing in the method name via `.then(reader.readFormat)` is redefining the context of `this`. Fix is to call `.then(() => reader.readFormat.then(() =>`
